### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by stephenogg** [centuri-engineering/cataloger#5]
Hi Guillaume -
I enjoyed your flash talk for the OME community 2021 meeting and wanted to play with cataloger on my omero installation to see if it would be potentially useful for my local users. I'm a docker newbie so there is probably something I'm doing wrong. I was able to install docker and docker-compose on an Ubuntu VM, clone your repository, create a .env file with my server details and a Bioportal API key, but when I try to intialise the db I get the following:

steve@steve-virtual-machine:~/repos/cataloger$ docker-compose run --rm manage db init
Creating network "cataloger_cataloger" with the default driver
Creating volume "cataloger_node-modules" with default driver
Creating volume "cataloger_static-build" with default driver
Creating volume "cataloger_db_data" with default driver
Creating volume "cataloger_backup" with default driver
Pulling cataloger_db (postgres:11)...
11: Pulling from library/postgres
fa1690ae9228: Pull complete
a73f6e07b158: Pull complete
973a0c44ddba: Pull complete
07e5342b01d4: Pull complete
578aad0862c9: Pull complete
a0b157088f7a: Pull complete
6c9046f06fc5: Pull complete
ae19407bdc48: Pull complete
71808c4e3b60: Pull complete
c43648409b9f: Pull complete
c1a5e1fce088: Pull complete
557a0805fba2: Pull complete
e953cab3dee4: Pull complete
7029159b5f65: Pull complete
Digest: sha256:4131c293772bbcbe10e4f2f18807a58252d0a4fdc246a467805e19bdc740925e
Status: Downloaded newer image for postgres:11
Creating cataloger_cataloger_db_1 ... error

ERROR: for cataloger_cataloger_db_1  Cannot create container for service cataloger_db: failed to mount local volume: mount /home/steve/data/cataloger:/var/lib/docker/volumes/cataloger_db_data/_data, flags: 0x1000: no such file or directory

ERROR: for cataloger_db  Cannot create container for service cataloger_db: failed to mount local volume: mount /home/steve/data/cataloger:/var/lib/docker/volumes/cataloger_db_data/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.

I guessed this might be a permissions error that my user doesn't have permission to mount some directory, but running the same command with sudo produced this:

steve@steve-virtual-machine:~/repos/cataloger$ sudo docker-compose run --rm manage db init
ERROR: Configuration for volume db_data specifies "device" driver_opt /root/data/cataloger, but a volume with the same name uses a different "device" driver_opt (/home/steve/data/cataloger). If you wish to use the new configuration, please remove the existing volume "cataloger_db_data" first:
$ docker volume rm cataloger_db_data

Can you help me out?
Thanks!
Steve

**Comment by glyg** [comment]
Hi, thanks for your interest in cataloger! You have to create the hosts directory prior to launching the volume, so `/home/steve/data/cataloger` needs to exists prior to launching docker-compose 
as you already created a volume, you need to run `docker-compose down` to make sure the old volume is not in use anymore, and then the `docker volume rm cataloger_db_data` command they propose

**Comment by glyg** [comment]
I've haded a section in the README:
 
https://github.com/centuri-engineering/cataloger/blob/main/README.md#create-host-side-directories

**Comment by stephenogg** [comment]
Thanks! That solved my problem.
